### ISSUE TITLE
Navigating to the site gives SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by crazymykl** [codykrieger/gfx.io#2]
I'd image you need a new cert. This also breaks updates in the app itself, although there are no updates available anyhow.

**Comment by codykrieger** [comment]
Weird...I’ve got CloudFlare in front of the site. What OS are you on?

**Comment by crazymykl** [comment]
I'm on High Sierra, and none of the main 3 browsers can do it (although I only have Chrome Canary on this box, not stable).

**Comment by codykrieger** [comment]
Really strange. I’m on High Sierra and iOS 11.2 and I’m not able to reproduce. Maybe a Cloudflare edge configuration issue? I’ll see if I can poke them to regenerate the certificate or something.

**Comment by crazymykl** [comment]
It appears to go away if I tether to my phone, so it looks like it's a problem with this wifi network. Sorry about that.

**Comment by crazymykl** [comment]
Actually, I ssh'd home and tried to `wget` it, and I am also getting a TLS fail, so I think this is a legit problem.

**Comment by codykrieger** [comment]
Hrmph: https://community.cloudflare.com/t/cannot-open-my-website-getting-ssl-error-no-cypher-overlap-error-after-activating-cloudflare/8275/14

**Comment by crazymykl** [comment]
Looks like Cloudflare fixed their end. Thanks for looking at this.
